before:
  hooks:
    - go mod tidy
    - go get -v
    - rm -rf dist
builds:
-
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w
  goos:
    - darwin
    - linux
  goarch:
    - amd64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: davegallant
    name: vpngate
