before:
  hooks:
    - go mod tidy
    - go get -v
    - rm -rf dist
builds:
-
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w
  goos:
    - darwin
    - linux
  goarch:
    - amd64
    - arm
    - arm64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: davegallant
    name: vpngate

# Check https://goreleaser.com/customization/homebrew/
brews:
  - homepage: 'https://github.com/davegallant/homebrew-public'
    description: 'a client for vpngate.net'
    folder: Formula
    commit_author:
      name: davegallant
      email: davegallant@gmail.com
    tap:
      owner: davegallant
      name: homebrew-public
